#!/usr/bin/env bash
set -e
sourcelib bash

echo "Enter machine's hostname:"
read hostname

echo "Enter timezone (format: Continent/City; more info at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones):"
read timezone

save $FLUX_HOME/env/host hostname timezone
