#!/usr/bin/env bash
set -e
fluxlib bash

. "$FLUX_HOME/env/user"
. "$FLUX_HOME/env/host"

template="$FLUX_HOME/env/nixos/autoconfig.tmp"
file="$FLUX_HOME/env/nixos/autoconfig.nix"

cp "$template" "$file"

com="sed -i"


for var in username fullname hostname timezone
do
    #sleep 1
    clnvar=${!var//\//\\\/}
    com="$com -e 's;\$$var;$clnvar;g'"
done

eval "$com $file"
