#!/usr/bin/env bash
set -e
fluxlib bash

. "$FLUX_HOME/env/user"
. "$FLUX_HOME/env/host"

template="$FLUX_HOME/env/nixos/autoconfig.tmp"
file="$FLUX_HOME/env/nixos/test.nix"

cp "$template" "$file"


for var in username fullname hostname timezone
do
    clnvar=${!var//\//\\\/}
    sub $file "\$$var" "$clnvar" > "$file"
done


# tr
# printf
# PE = parameter expansion
# printf/PE can escape. tr can replace/delete. PE can be used to delete.
