#!/usr/bin/env bash
set -e
sourcelib bash

# Load variables
. "$FLUX_HOME/env/user"
. "$FLUX_HOME/env/host"
configname="$1"
if [[ -z $configname ]]
    then
        . "$FLUX_HOME/env/config"
fi

# Refresh build directory
rm "$FLUX_HOME"/env/nixos/build/*
cp "$FLUX_HOME"/env/nixos/$configname/* "$FLUX_HOME/env/nixos/build"

# Build templates into nix files

templates=$(find "$FLUX_HOME/env/nixos/build" -name "*.tmp")

for file in $templates
    do
        maketemp "${file:0:-4}".{tmp,nix}
done

rm $templates

# Build configuration file

makeconfig "$FLUX_HOME/env/nixos/build"

# Add custom (i.e. user supplied) options into the build

cp "$FLUX_HOME"/env/nixos/custom.nix "$FLUX_HOME/env/nixos/build"

