#!/usr/bin/env bash
set -e
fluxlib bash

echo "Enter your user name:"
read username

echo "Enter your full name or alias:"
read fullname

echo "Enter the hostname (the name you wish your machine to have on the network):"
read hostname

save $FLUX_HOME/env/nixos/$username.usr username fullname hostname